
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: myapps.viadee.de
spec:
  group: viadee.de
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                replicas:
                  type: integer
                  minimum: 1
  scope: Namespaced
  names:
    plural: myapps
    singular: myapp
    kind: MyApp
---
apiVersion: myapp.viadee.de/v1
kind: MyApp
metadata:
  name: myapp-instance
spec:
  replicas: 2