# permissions for end users to edit rookcephfsrefvols.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rookcephfs-refvolume-operator
    app.kubernetes.io/managed-by: kustomize
  name: rookcephfsrefvol-editor-role
rules:
- apiGroups:
  - operator.dotv.home.arpa
  resources:
  - rookcephfsrefvols
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.dotv.home.arpa
  resources:
  - rookcephfsrefvols/status
  verbs:
  - get
