
---
apiVersion: operator.dotv.home.arpa/v1
kind: RookCephFSRefVol
metadata:
  name: refvol-1
spec:
  datasource:
    pvcInfo:
      pvcName: cephfs-pvc-9b9j9
      namespace: default
    pvcSpec:
      createIfNotExists: true
      storageClassName: rook-cephfs
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  destination:
    pvcInfo:
      pvcName: cephfs-pvc-9b9j9
      namespace: others
  cephFsUserSecretName: rook-csi-cephfs-node-user

