apiVersion: operator.dotv.home.arpa/v1
kind: RookCephFSRefVol
metadata:
  labels:
    app.kubernetes.io/name: rookcephfs-refvolume-operator
    app.kubernetes.io/managed-by: kustomize
  name: test
spec:
  pvcName: cephfs-pvc-2
  namespace: default
  cephFsUserSecretName: rook-csi-cephfs-node-user
  # TODO(user): Add fields here
